# Generated by Django 5.2.16 on 2026-08-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('content', models.TextField(help_text='Detailed blog content in Markdown')),
                ('image_url', models.CharField(blank=True, help_text='Header image URL', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=150)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blogs.blogcategory')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
